### ISSUE TITLE
issue with sphinx in pom.xml

### ISSUE THREAD

**Issue by anirudh-hegde** [Spayker/speech2text#1]
<dependency>
            <groupId>edu.cmu.sphinx</groupId>
            <artifactId>sphinx4-core</artifactId>
            <version>5.0.1</version>
        </dependency>
when I add this 
Its shows error that The POM for edu.cmu.sphinx:sphinx4-core:jar:5.0.1 is missing
can someone please help me out

**Comment by Spayker** [comment]
Cause it does not exist in Maven central repo: https://mvnrepository.com/artifact/net.sf.phat/sphinx4-core . Attach separate repo where 5.0.1 exists or avoid pom modification by manual attaching of 5.0.1 to you project.

**Comment by anirudh-hegde** [comment]
> Cause it does not exist in Maven central repo: https://mvnrepository.com/artifact/net.sf.phat/sphinx4-core . Attach separate repo where 5.0.1 exists or avoid pom modification by manual attaching of 5.0.1 to you project.

Ya thank you sir, As I just completed my college mini-project
